val exception = 1 / 0